### ISSUE TITLE
Footer too big/ event section not fully scrolling

### ISSUE THREAD

**Issue by oa495** [TechAtNYU/cal#2]
![img_0282](https://cloud.githubusercontent.com/assets/8635106/10338398/df49c3d2-6cd3-11e5-8ad4-1a020aa1130a.jpg)

the footer takes up too much space on the mobile phone and even when you scroll you are unable to see the full list of events.

**Comment by grungerabbit** [comment]
noted. pretty awesome what happens when you go to the link on iOS btw

Also - maybe the calendar should be scoped only to this year? what do we think? Because DemoDays from 2012 is showing up...

![slack for ios upload png](https://cloud.githubusercontent.com/assets/1840745/10338948/d37908b2-6cd6-11e5-8639-6f39f7866869.jpeg)

**Comment by oa495** [comment]
@grungerabbit for the actual calendar it's only getting events from this year. I don't know how the ics calendar works but I think it should also be events from this year as well.

**Comment by grungerabbit** [comment]
alright, so this is actually a problem for https://github.com/TechAtNYU/calendar-service lol. will add a comment there
